name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
    
env:
    DOTNET_VERSION: 6.0.417  # select a 'sdk'.'version' from https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/7.0/releases.json
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    configuration: Release

defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - run: dotnet build tests/JBN.Tests.csproj --configuration ${{ env.configuration }}
        
    - name: Unit test
      run: dotnet test tests/JBN.Tests.csproj --configuration ${{ env.configuration }}
